### ISSUE TITLE
Navbar logo doesn't bring me to the home page

### ISSUE THREAD

**Issue by LieutenantRice** [getgrav/grav-skeleton-notepad-site#1]
Hey again,

I've been trying my best to figure out how to get the main logo to bring you to the homepage when clicked on. Currently it just refreshes the current page. I'm _pretty_ sure it was like this when I first installed but just kept developing hoping to fix it later. I've tried going into base.html.twig & page-no-header.html.twig and added the url in manually in the <a> tag. But had no luck. I get this inside inspect element, even when I put a URL in the code.
<img width="275" alt="screen shot 2016-06-01 at 7 20 28 pm" src="https://cloud.githubusercontent.com/assets/7194968/15718929/f2b00c40-282d-11e6-9990-ea9e0f44ea4c.png">

Here's my page if you can take a look.
http://protomod.net/discord

Thanks for all the support.

**Comment by rhukster** [comment]
This is what is used in Antimatter:

```
<a href="{{ base_url == '' ? '/' : base_url }}">...</a>
```

**Comment by LieutenantRice** [comment]
Yeah but this isn't antimatter :P I'm using Notepad.

**Comment by rhukster** [comment]
Yes but the link will work the same

**Comment by LieutenantRice** [comment]
I've just added it to base.html.twig and still get the same problem.

`<a class="summer-blog-logo" href="{{ base_url == '' ? '/' : base_url }}"><img src="{{ base_url_relative }}{{ site.logo }}" alt="ProtoMod Logo" /></a>`

**Comment by flaviocopes** [comment]
`{{ base_url }}` points to the current page URL instead of the site base url? 
If so, looks like an issue I'm tracking.

Are you trying in localhost, or on a server? Which web server?

**Comment by LieutenantRice** [comment]
That's correct. Here is the URL. I've tried a few things all with no success. Maybe there is some admin setting I've missed out on. Although it seems to be the case on 2 of my websites. Both with different themes.

Notepad Theme: http://protomod.net/discord
Future Theme:    http://uxvi.be/forum-muut

Try clicking the main logo from those pages and you'll see it just refreshes.

**Comment by flaviocopes** [comment]
Is it possible for you to create me a temporary FTP/SSH account on that server, so I can try checking what's the issue? If yes, PM the details to me via Gitter
